app:
  port: 8000
database:
  host: localhost
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "muttr"
mailer:
  base_url: "localhost:2525"
  sender_email: "no-reply@muttr.com"