app:
  port: 8000
database:
  host: localhost
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "muttr"
mailer:
  host: localhost
  port: 2525
  username: noreply
  password: password